from typing import Protocol


class IdentityRepository(Protocol):
    async def create_user(self, user: dict) -> bool: ...
    async def find_user(self, email: str) -> dict | None: ...
    async def get_user(self, user_id: str) -> dict | None: ...
    async def create_session(self, session: dict) -> None: ...
    async def get_session(self, session_id: str) -> dict | None: ...
    async def rotate_session(
        self, session_id: str, old_digest: str, new_digest: str, now
    ) -> bool: ...
    async def revoke_session(self, session_id: str) -> None: ...
    async def set_reset(self, user_id: str, digest: str, expires_at) -> None: ...
    async def reset_password(self, digest: str, password_hash: str, now) -> bool: ...
    async def allow_request(self, key: str, now, limit: int) -> bool: ...


class PasswordHasher(Protocol):
    async def hash(self, password: str) -> str: ...
    async def verify(self, password: str, password_hash: str) -> bool: ...


class Tokens(Protocol):
    def issue(self, user: dict, session: dict, expires_at) -> str: ...
    def decode(self, token: str) -> dict: ...


class Mailer(Protocol):
    async def password_reset(self, email: str, token: str) -> None: ...
